name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - run: cargo build --verbose
    - run: cargo test --verbose
